version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: form-urlencoded
    versions:
    - 4.4.2
    - 6.0.0
